
# Задание №2 ✅


> Написать программу, которая вычисляет площадь фигуры, параметры которой подаются на вход. Фигуры, которые подаются на вход: треугольник, прямоугольник, круг. Результатом работы является словарь, где ключ – это название фигуры, а значение – это площадь.

Входные данные: название фигуры, параметры

## Объяснение

Будем использовать простые формулы для вычисления **площадей** треугольника, прямоугольника и круга.

Напишем программу, которая принимает название фигуры и соответствующие параметры, а затем возвращает словарь с названием фигуры и её площадью.

1. Рассматрим три фигуры:

*   Треугольник: нужны два параметра - основание и высота.
*   Прямоугольник: нужны два параметра - длина и ширина.
*   Круг: нужен один параметр - радиус.

2. Будем использовать следующие формулы для вычисления площади:

> Треугольник: 0.5 x основание x выботв

> Прямоугольник: Площадь = длина × ширина

> Круг: π × радиус^2

3. Для хранения результата используем словарь, где:


*  Ключ (figure) - это название фигуры.

*  Значение - это вычисленная площадь этой фигуры.

4. Допишем код так, чтобы результаты были корректны.

*  Введено отрицательное значение;
*  Введена не та фигура из 3х.

![image.png]()

![image.png]()

✅ Ввод только 3х фигур

✅ Правильный подсчет при отрицательных значениях

## Код

In [ ]:
import math

def calculate_area(figure, *params):
    # Определяем площадь треугольника
    if figure == "треугольник":
        if len(params) != 2 or params[0] <= 0 or params[1] <= 0:
            raise ValueError("Для треугольника нужны положительные основание и высота.")
        return 0.5 * params[0] * params[1]

    # Определяем площадь прямоугольника
    elif figure == "прямоугольник":
        if len(params) != 2 or params[0] <= 0 or params[1] <= 0:
            raise ValueError("Для прямоугольника нужны положительные длина и ширина.")
        return params[0] * params[1]

    # Определяем площадь круга
    elif figure == "круг":
        if len(params) != 1 or params[0] <= 0:
            raise ValueError("Для круга нужен положительный радиус.")
        return math.pi * params[0]**2

    else:
        raise ValueError("Некорректный ввод.")

def main():
    results = {}  # Инициализация словаря для хранения результатов
    while True:
        # Запрашиваем у название фигуры
        figure = input("Введите название фигуры (треугольник, прямоугольник, круг) или 'стоп' для завершения: ").strip().lower()
        if figure == "стоп":  # Проверка условия для завершения ввода
            break

        try:
            # Ввод параметров в зависимости от фигуры
            if figure == "треугольник":
                params = [float(input("Введите основание треугольника: ")), float(input("Введите высоту треугольника: "))]
            elif figure == "прямоугольник":
                params = [float(input("Введите длину прямоугольника: ")), float(input("Введите ширину прямоугольника: "))]
            elif figure == "круг":
                params = [float(input("Введите радиус круга: "))]
            else:
                raise ValueError("Некорректный ввод.")

            # Вычисляем площадь фигуры и добавляем результат в словарь
            results[figure] = calculate_area(figure, *params)

        except ValueError as e:
            print("Ошибка:", e)  # Вывод сообщения об ошибке

    print("Итоговые результаты:", results)

In [ ]:
if __name__ == "__main__":
    main()  # Запуск основной функции

# Задание №3 ✅

> Написать программу, которая на вход получает два числа и операцию, которую к ним нужно применить.
Должны быть реализованы следующие операции: +, -, /, //, abs – модуль, pow или ** – возведение в степень

 Результатом работы программы является одно число.

## Объяснение

1. Ввод данных

Запрашиваем у пользователя два числа и операцию, которую он хочет выполнить над этими числами.


2. Проверка операции:

Проверить, что введенная операция соответствует одной из поддерживаемых операций (+, -, /, //, abs, pow или **).
Если операция не соответствует ни одной из поддерживаемых, вывести сообщение об ошибке.

3. Выполнение операции и вывод

4. Обработка исключений:

Обработать исключения, такие как деление на ноль при операциях деления (/, //).

## Код

### Вариант 1

In [ ]:
def calculate(num1, num2, operation):
    if operation == '+': return num1 + num2
    elif operation == '-': return num1 - num2
    elif operation == '/': return num1 / num2 if num2 != 0 else None
    elif operation == '//': return num1 // num2 if num2 != 0 else None
    elif operation == 'abs': return abs(num1), abs(num2)
    elif operation in ['pow', '**']: return pow(num1, num2)
    else: raise ValueError("Некорректная операция.")

def main():
    try:
        num1, num2 = float(input("Введите первое число: ")), float(input("Введите второе число: "))
        operation = input("Введите операцию (+, -, /, //, abs, pow, **): ").strip()

        if operation in ['abs']:
            result = calculate(num1, num2, operation)
            print(f"Результат: abs({num1}) = {result[0]}, abs({num2}) = {result[1]}")
        else:
            print(f"Результат: {calculate(num1, num2, operation)}")

    except ValueError as e:
        print("Ошибка:", e)

if __name__ == "__main__":
    main()

### Вариант 2

In [ ]:
def str_operation(a: float, b: float, operation: str):
    str_expr = str(a) + operation + str(b)

    try:
        x = eval(str_expr)

    except Error:
        print ("При вводе допущена ошибка. Попробуйте еще раз.")

    return x

In [ ]:
str_operation(2, 5, '^')

# Задание 4 ✅

Напишите программу, которая считывает с консоли числа (по одному в строке) до тех пор, пока сумма введённых чисел не будет равна 0 и после этого выводит сумму квадратов всех считанных чисел.

In [ ]:
if __name__ == '__main__':
    numbs = []
    sum_numbs = 0

    while True:
        num = int(input("Число: "))
        numbs.append(num)
        sum_numbs += num

        if sum_numbs == 0:
            break

    sum_squares = sum([n ** 2 for n in numbs])
    print("sum:", sum_squares)

Число: 2
Число: -2
sum: 8

# Задание 5✅

In [ ]:
# Вводим число N
N = int(input("Введите неотрицательное целое число N: "))

# Создаем список для хранения чисел
result = []

# Наполняем список числами по описанным правилам
for i in range(1, N + 1):
    if len(result) < N:  # проверяем, не превышает ли длина списка N
        result.extend([i] * i)
    if len(result) >= N:  # если длина списка больше или равна N, выходим из цикла
        break

# Обрезаем список до нужной длины N
result = result[:N]

# Выводим элементы списка через пробел
print(*result)

Введите неотрицательное целое число N: 7
1 2 2 3 3 3 4

# Задание 6✅

Даны два списка: А = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2] В = [‘a’, ’b’, ’c’, ’c’, ’c’, ’b’, ’a’, ’c’, ’a’, ’a’, ’b’, ’c’, ’b’, ’a’] Создать словарь, в котором ключи – это содержимое списка В, а значения для ключей словаря – это сумма всех элементов списка А в соответствии с буквой, содержащийся на той же позиции в списке В. Пример результата программы: {‘a’ : 10, ‘b’ : 15, ‘c’ : 6}.

In [ ]:
a = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]
b = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']
d = {'a': 0, 'b': 0, 'c': 0}

if __name__ == '__main__':
    for i in range(len(b)):
        if b[i] == 'a':
            d['a'] += a[i]
        elif b[i] == 'b':
            d['b'] += a[i]
        elif b[i] == 'c':
            d['c'] += a[i]

    print("Dictionary:", d)

Dictionary: {'a': 17, 'b': 11, 'c': 17}

# Задание 7

Скачать и загрузить данные о стоимости домов в калифорнии,
используя библиотеку sklearn.

In [ ]:
pip install pandas scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Загрузка данных
california_housing = fetch_california_housing()

# Преобразование данных в DataFrame
df = pd.DataFrame(data=california_housing.data, columns=california_housing.feature_names)
df['target'] = california_housing.target

# Вывод первых 5 строк DataFrame
print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude  target
0    -122.23   4.526
1    -122.22   3.585
2    -122.24   3.521
3    -122.25   3.413
4    -122.25   3.422

# Задание 8-10✅

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Загрузка данных
california_housing = fetch_california_housing()

# Преобразование данных в DataFrame
df = pd.DataFrame(data=california_housing.data, columns=california_housing.feature_names)
df['target'] = california_housing.target

# Вывод первых 5 строк DataFrame
print(df.head())

# Использование метода info() для получения информации о DataFrame
print(df.info())
# Узнать, есть ли пропущенные значения
print(df.isna().sum())
#Возраст
print(df.loc[(df['HouseAge'] > 50) & (df['Population'] > 2500)])

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude  target
0    -122.23   4.526
1    -122.22   3.585
2    -122.24   3.521
3    -122.25   3.413
4    -122.25   3.422
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   target      20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB
None
MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
target        0
dtype: int64
       MedInc  HouseAge  AveRooms  AveBedrms  Population    AveOccup  \
460    1.4012      52.0  3.105714   1.060000      3337.0    9.534286
4131   3.5349      52.0  4.646119   1.047945      2589.0    5.910959
4440   2.6806      52.0  4.806283   1.057592      3062.0    4.007853
5986   1.8750      52.0  4.500000   1.206349      2688.0   21.333333
7369   3.1901      52.0  4.730942   1.017937      3731.0    4.182735
8227   2.3305      52.0  3.488860   1.170380      3018.0    3.955439
13034  6.1359      52.0  8.275862   1.517241      6675.0  230.172414
15634  1.8295      52.0  2.628169   1.053521      2957.0    4.164789
15652  0.9000      52.0  2.237474   1.053535      3260.0    2.237474
15657  2.5166      52.0  2.839075   1.184049      3436.0    1.621520
15659  1.7240      52.0  2.278566   1.082348      4518.0    1.780142
15795  2.5755      52.0  3.402576   1.058776      2619.0    2.108696
15868  2.8135      52.0  4.584329   1.041169      2987.0    3.966799

       Latitude  Longitude   target
460       37.87    -122.26  1.75000
4131      34.13    -118.20  1.93600
4440      34.08    -118.21  1.53000
5986      34.10    -117.71  2.12500
7369      33.97    -118.21  1.67600
8227      33.78    -118.20  1.62500
13034     38.69    -121.15  2.25000
15634     37.80    -122.41  2.43800
15652     37.80    -122.41  5.00001
15657     37.79    -122.41  2.75000
15659     37.79    -122.41  2.25000
15795     37.77    -122.42  3.25000
15868     37.76    -122.41  2.60300

NameError: name 'data' is not defined

# Задание 11✅

Узнать максимальное и минимальное значения медианной стоимости дома.

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Загрузка данных
california_housing = fetch_california_housing()

# Преобразование данных в DataFrame
df = pd.DataFrame(data=california_housing.data, columns=california_housing.feature_names)
df['target'] = california_housing.target

# Получение первых 5 значений целевой переменной
median_house_prices = df['target'].head()

# Вычисление максимальной и минимальной стоимости
max_price = max(median_house_prices)
min_price = min(median_house_prices)

print("max:", max_price)
print("min:", min_price)

max: 4.526
min: 3.413

# Задание 12✅

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Загрузка данных
california_housing = fetch_california_housing()

# Преобразование данных в DataFrame
df = pd.DataFrame(data=california_housing.data, columns=california_housing.feature_names)
df['target'] = california_housing.target

# Применение метода apply() для вычисления среднего значения по каждому признаку
def print_feature_mean(column):
    print(f'{column.name}: {column.mean()}')

df.apply(print_feature_mean)

MedInc: 3.8706710029069766
HouseAge: 28.639486434108527
AveRooms: 5.428999742190376
AveBedrms: 1.096675149606208
Population: 1425.4767441860465
AveOccup: 3.0706551594363742
Latitude: 35.63186143410853
Longitude: -119.56970445736432
target: 2.068558169089147

MedInc        None
HouseAge      None
AveRooms      None
AveBedrms     None
Population    None
AveOccup      None
Latitude      None
Longitude     None
target        None
dtype: object

# Задание 1*

В одной строке вам дан текст, который состоит из латинских
букв и пробелов. Дан текст на английском языке. Необходимо закодировать его с помощью азбуки Морзе, где каждой букве соответствует последовательность точек и тире.

In [ ]:
def text_to_morse(text):
    morse_code_dict = {
        'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.',
        'G': '--.', 'H': '....', 'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..',
        'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
        'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
        'Y': '-.--', 'Z': '--..', ' ': '/', ':': '---...'
    }

    text = text.upper()  # Приведение текста к верхнему регистру
    morse_code = ' '.join(morse_code_dict.get(char, '') for char in text)

    return morse_code

# Пример использования:
input_text = (input("Текст: "))
encoded_text = text_to_morse(input_text)
print(encoded_text)

Текст: start
... - .- .-. -

# Задание 2*

В некотором городе открывается новая служба по доставке электронных
писем. Необходимо наладить систему регистрации новых
пользователей.
Регистрация должна работать следующим образом: если новый
пользователь хочет зарегистрироваться на сайте, то он должен послать
системе запрос name со своим именем. Система должна определить,
существует ли уже такое имя в базе данных. Если такого имени не
существует, то оно заносится в базу данных системы и пользователю
возвращается ответ "ОК", подтверждающий успешную регистрацию. А
если пользователь с таким именем уже существует, то система должна
сформировать новое имя и выдать его пользователю в качестве
подсказки, при этом сама подсказка также добавляется в базу данных.
Новое имя формируется следующим образом: к name последовательно
приписываются числа, начиная с 1 (name1, name2 и так далее), и среди
них находят такое наименьшее i, что namei еще не содержится в системе.
Входные данные
В первой строке входных данных задано число n (1 ≤ n ≤ 100000).
Следующие n строк содержат запросы к системе. Каждый запрос
представляет собой непустую строку длиной не более 32 символов,
состоящую только из строчных букв латинского алфавита.
Выходные данные
В выходных данных должно содержаться n строк – ответы системы на
запросы: "OK" в случае успешной регистрации, или подсказка с новым
именем, если запрашиваемое уже занято.

In [ ]:
# Чтение количества запросов
n = int(input())

# Словарь для хранения количества встреченных имен
database = {}

# Обработка каждого запроса
for _ in range(n):
    name = input()

    if name not in database:
        # Если имя не встречалось, регистрируем его и выводим "OK"
        database[name] = 0
        print("OK")
    else:
        # Если имя уже существует, генерируем новое уникальное имя
        database[name] += 1
        new_name = f"{name}{database[name]}"
        print(new_name)
        database[new_name] = 0  # Новое имя также заносим в базу данных

3
b
OK
b
b1
b
b2

# Задание 3*

In [ ]:
# Ввод количества файлов
n = int(input("Введите количество файлов: "))

# Словарь для хранения прав доступа к файлам
file_permissions = {}

# Вводим информацию о файлах и их разрешенных операциях
for _ in range(n):
    data = input().split()
    filename = data[0]
    operations = data[1:]
    file_permissions[filename] = operations

# Ввод количества запросов
m = int(input("Введите количество запросов: "))

# Обработка запросов
for _ in range(m):
    operation, filename = input().split()

    # Преобразуем операции к формату (write -> w, read -> r, execute -> x)
    if operation == "write":
        action = "w"
    elif operation == "read":
        action = "r"
    elif operation == "execute":
        action = "x"

    # Проверяем, допустима ли операция на файле
    if action in file_permissions.get(filename, []):
        print("OK")
    else:
        print("Access denied")

Введите количество файлов: 2
1.txt
2.txt
Введите количество запросов: 2
write 1.txt
Access denied
write 2.txt
Access denied